- name: Restore Windows server roles
  ansible.windows.win_shell: |
    Import-Module ServerManager
    Import-Csv "{{ web_api_migration_backup_dir }}\server_roles.csv" |
    ForEach-Object { Install-WindowsFeature $_.Name }