- name: Configure environment variables are present
  ansible.windows.win_environment:
    state: present
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    level: machine
  loop: "{{ environment_variables | dict2items }}"
  
