# Expects: pkg (one resolved_item)

# 1) Precheck
- name: Check if software already installed (marker)
  ansible.windows.win_stat:
    path: "{{ pkg.install.check.path_exists }}"
  register: marker_check

- name: Set installed flag
  ansible.builtin.set_fact:
    _pkg_is_installed: "{{ marker_check.stat.exists | bool }}"

# 2) Acquire/Transfer (only if not installed)
- name: Acquire from jfrog
  ansible.builtin.include_tasks: acquire_jfrog.yml
  when:
    - not _pkg_is_installed
    - pkg.source.type == "jfrog"

- name: Validate local installer exists (local)
  ansible.windows.win_stat:
    path: "{{ pkg.installer.final_path }}"
  register: installer_file
  when:
    - not _pkg_is_installed
    - pkg.source.type == "local"

- name: Fail if local installer missing
  ansible.builtin.assert:
    that:
      - installer_file.stat.exists
    fail_msg: "Installer not found at {{ pkg.installer.final_path }}"
  when:
    - not _pkg_is_installed
    - pkg.source.type == "local"

# 3) Install
- name: Install package (EXE)
  ansible.windows.win_package:
    path: "{{ pkg.installer.final_path }}"
    arguments: "{{ pkg.install.arguments }}"
    state: present
  when:
    - not _pkg_is_installed
    - pkg.install.type == "exe"

   # 3) Install
- name: Install package (MSI)
  ansible.windows.win_package:
    path: "{{ pkg.installer.final_path }}"
    arguments: "{{ pkg.install.arguments }}"
    state: present
  when:
    - not _pkg_is_installed
    - pkg.install.type == "msi" 

# 4) Verify
- name: Verify installation marker
  ansible.windows.win_stat:
    path: "{{ pkg.install.check.path_exists }}"
  register: verify_marker

- name: Ensure installation succeeded
  ansible.builtin.assert:
    that:
      - verify_marker.stat.exists
    fail_msg: "Installation failed for {{ pkg.software_key }}"