- name: Validate jfrog fields
  ansible.builtin.assert:
    that:
      - sw.source.url is defined
      - sw.source.filename is defined
      - installer_cache_dir is defined
    fail_msg: >-
      Software '{{ software_key }}' (jfrog) must define:
      source.url, source.filename and installer_cache_dir must be set.

- name: Build cache path for jfrog artifact
  ansible.builtin.set_fact:
    jfrog_cache_path: "{{ installer_cache_dir }}\\{{ software_key }}\\{{ sw.source.filename }}"

- name: Set resolved item (jfrog)
  ansible.builtin.set_fact:
    _resolved_item_overrides:
      software_key: "{{ software_key }}"

      source:
        type: "jfrog"
        original_path: "{{ sw.source.url }}"
        bearer_token: "{{ jfrog_bearer_token }}"
        
      installer:
        final_path: "{{ jfrog_cache_path }}"
        filename: "{{ sw.source.filename }}"

      install:
        type: "{{ sw.install.type }}"
        arguments: "{{ sw.install.arguments | default('') }}"
        destination: "{{ sw.install.destination | default('') }}"
        check:
          path_exists: "{{ sw.install.check.path_exists }}"

      path: "{{ sw.path | default(omit)}}"

      env: "{{ sw.env | default(omit)}}"

- name: Override values with calculated ones (jfrog)
  ansible.builtin.set_fact:
    resolved_item: "{{ sw | combine(_resolved_item_overrides | default({}), recursive=True) }}"