- name: Ensure machine environment variables are present
  ansible.windows.win_environment:
    level: machine
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
  loop: "{{ machine_env_variables | dict2items }}"
