spec:
  inputs:
    environment:
      type: string
      default: lab
      options:
        - lab
        - dev
        - tst
        - prd
        - sandbox
      description: "Target inventory environment"

    domain:
      type: string
      default: toolbox
      options:
        - toolbox
        - platform
      description: "Deployment domain"

    target:
      type: string
      description: "Playbook target"
      rules:
        - if: $[[ inputs.domain ]] == 'toolbox'
          options:
            - team_alpha
            - team_beta
            - team_gamma
            - team_neon
          default: team_alpha
        - if: $[[ inputs.domain ]] == 'platform'
          options:
            - uipath_orchestrator
            - uipath_test_manager
          default: uipath_orchestrator

stages:
  - codestyle
  - verify
  - fetch-secrets
  - deploy

default:
  image: python:3.11-slim
  before_script:
    - python --version
    - pip install --no-cache-dir ansible
    - ansible-playbook --version


codestyle:
  stage: codestyle
  script:
      - echo "Linting will be used here from component from dso team"

secrets-ansible-sevice-accounts:
  stage: fetch-secrets
  script:
      - echo "secrets fetched from vault using the component from dso team"      

vault-token:
  stage: fetch-secrets
  script:
      - echo "vault token will be fetched using the component from dso team"      

verify-roles:
  stage: verify
  script:
    - ansible-playbook -i inventories/$[[ inputs.environment ]]/hosts.yml playbooks/windows/$[[ inputs.domain ]]/$[[ inputs.target ]].yml --syntax-check


deploy-$[[inputs.environment]]-$[[inputs.domain]]-$[[inputs.target]]:
  stage: deploy
  when: manual
  script:
    - ansible-playbook -i inventories/$[[ inputs.environment ]]/hosts.yml playbooks/windows/$[[ inputs.domain ]]/$[[ inputs.target ]].yml
