---

- name: UiPath | Resolve bootstrap installer package
  ansible.builtin.set_fact:
    resolved_packages: []

- name: UiPath | Resolve UiPath installer from software catalog
  ansible.builtin.include_tasks: ../../common/tasks/resolve_installer.yml
  vars:
    software_key: "{{ item }}"
    software_catalog_entry: uipath_orchestrator_migration.yml
    software_catalog_force_reload: true
  loop: "{{ uipath_orchestrator_packages }}"
  loop_control:
    label: "{{ item }}"



- name: Execute installation plan 
  ansible.builtin.include_tasks: ../../common/tasks/execute_plan.yml
  loop: "{{ resolved_packages }}"
  loop_control:
    loop_var: pkg
