---
- name: Execute UiPath migration stages
  ansible.builtin.include_tasks: "{{ item }}"
  loop:
    - fetch_thumprint.yml
    - external_validation.yml
    - enable_iis_features.yml
    - install_orchestrator.yml    
    - post_installation_changes.yml
    - windows_auth_scoped_tasks.yml
  loop_control:
    label: "{{ item }}"



