---
- name: Install Microsoft Web Deploy packages
  ansible.builtin.include_tasks: ../../common/tasks/install_from_catalog.yml
  vars:
    software_catalog_entry: microsoft_web_deploy.yml
    software_package_list: "{{ microsoft_web_deploy_packages | default([]) }}"
    software_role_name: microsoft_web_deploy
