---
- name: Install vscode packages
  ansible.builtin.include_tasks: ../../common/tasks/install_from_catalog.yml
  vars:
    software_catalog_entry: vscode.yml
    software_package_list: "{{ vscode_packages }}"
    software_role_name: vscode


