---
- name: Initialize resolved Microsoft .NET Framework package list
  ansible.builtin.set_fact:
    resolved_packages: []

- name: Resolve Microsoft .NET Framework packages
  ansible.builtin.include_tasks: ../../common/tasks/resolve_installer.yml
  loop: "{{ microsoft_dotnet_framework_packages | default([]) }}"
  loop_control:
    loop_var: software_key

- name: Execute Microsoft .NET Framework installation plan
  ansible.builtin.include_tasks: ../../common/tasks/execute_plan.yml
  loop: "{{ resolved_packages }}"
  loop_control:
    loop_var: pkg
  when: resolved_packages | length > 0
