---
- name: Install Microsoft .NET Framework packages
  ansible.builtin.include_tasks: ../../common/tasks/install_from_catalog.yml
  vars:
    software_catalog_entry: microsoft_dotnet_framework.yml
    software_package_list: "{{ microsoft_dotnet_framework_packages | default([]) }}"
    software_role_name: microsoft_dotnet_framework
