---
- name: Install IIS URL Rewrite packages
  ansible.builtin.include_tasks: ../../common/tasks/install_from_catalog.yml
  vars:
    software_catalog_entry: iis_url_rewrite.yml
    software_package_list: "{{ iis_url_rewrite_packages | default([]) }}"
    software_role_name: iis_url_rewrite
