all:
  children:
    windows:
      children:
        toolbox_servers:
          hosts:
            win_toolbox_01:

        team_toolbox_alpha:
          hosts:
            win_toolbox_01:

        uipath_orchestrator:
          hosts:
            win_orch_01:

        uipath_test_manager:
          hosts:
            win_tm_01:

    linux:
      children:
        linux_gitlab_runner:
          hosts:
            lin_runner_01: