all:
  children:
    windows:
      children:
        uipath_orchestrator:
          hosts:
            win_orch_lab_01:

        uipath_test_manager:
          hosts:
            win_tm_lab_01:
