---
- name: "Initialize resolved list"
  set_fact:
    resolved_packages: []

- name: "Resolve python packages"
  include_tasks: ../common/tasks/resolve_installer.yml
  loop: "{{ python_packages }}"
  loop_control:
    loop_var: software_key
  
- name: "Debug plan (python role)"
  when: debug_mode | bool
  block:
    - debug:
        msg: "================ ROLE: python ================"
    - debug:
        msg: |
          Software: {{ item.software_key }}
            Source Type: {{ item.source.type }}
            Original Path: {{ item.source.original_path }}
            Requires Transfer: {{ item.source.requires_transfer }}
            Final Installer Path: {{ item.installer.final_path }}
            Install Arguments: {{ item.install.arguments }}
      loop: "{{ resolved_packages }}"
    - debug:
        msg: "================================================"

- name: Add software paths
  ansible.builtin.include_tasks: add_path.yml
  loop: "{{ resolved_packages }}"
  loop_control:
    loop_var: pkg

- name: Add environment variables
  include_tasks: common/add_env.yml
  vars:
    env_variables: "{{ item.env.variables }}"
  when: item.env is defined and item.env.enabled | default(false)
  loop: "{{ resolved_packages }}"    

- name: Add registry entries
  include_tasks: common/add_registry.yml
  vars:
    registry_entries: "{{ item.registry.entries }}"
  when: item.registry is defined and item.registry.enabled | default(false)
  loop: "{{ resolved_packages }}"

- name: Add certificates
  include_tasks: common/add_certificate.yml
  vars:
    certificate_entries: "{{ item.certificate.entries }}"
  when:
    - ansible_os_family == "Windows"
    - item.certificate is defined
    - item.certificate.enabled | default(false)  