all:
  children:
    windows:
      children:
        team_alpha:
          hosts:
            win_sandbox_01:

        team_beta:
          hosts:
            win_sandbox_01:    

        team_gamma:
          hosts:
            win_sandbox_01:    

        team_neon:
          hosts:
            win_sandbox_01:            

        uipath_orchestrator:
          hosts:
            win_sandbox_01:

        uipath_test_manager:
          hosts:
            win_sandbox_01:

    