- name: Retrieve all certificates from the LocalMachine 
  ansible.windows.win_certificate_info:      
      store_name: "{{ ssl_certificate.store_name }}"
      store_location: "{{ ssl_certificate.store_location }}"
  register: ssl_certificate_info

- name: Normalize the subject and filter for certificates matching the subject
  set_fact:
    matching_certificates: >-
      {{
        ssl_certificate_info.certificates
        | selectattr(
            'subject',
            'search',
            ssl_certificate.subject
            | replace('\\', '\\\\')
            | regex_replace('^"|"$', '') 
            | regex_replace(' OU = ', ', OU=')
            | regex_replace(' O = ', ', O=')
            | regex_replace(' L = ', ', L=')
            | regex_replace(' S = ', ', S=')
            | regex_replace(' C = ', ', C=')
          )
        | list
      }}

- name: Get current epoch time
  ansible.builtin.set_fact:
    current_epoch: "{{ lookup('pipe', 'date +%s') }}"          

- name: Filter for valid (non-expired) certificates
  set_fact:
    valid_certificates: >-
      {{
        matching_certificates | selectattr('valid_to', '>', current_epoch |int ) | list
      }}

- name: Import certificate if missing
  ansible.windows.win_certificate_store:
    path: "{{ ssl_certificate.pfx_path }}"
    password: "{{ _vault_secret.certificate }}"
    state: present
    store_location: "{{ ssl_certificate.store_location }}"
    store_name: "{{ ssl_certificate.store_name }}"
  when:    
    - valid_certificates | length == 0
  no_log: true