all:
  children:
    windows:
      children:
        team_neon:
          hosts:
            team_neon_01:

        team_alpha:
          hosts:
            team_alpha_01:

        team_beta:
          hosts:
            team_beta_01:

        team_gamma:
          hosts:
            team_gamma_01:

        uipath_orchestrator:
          hosts:
            win_orch_prd_01:

        uipath_test_manager:
          hosts:
            win_tm_prd_01:
